
# 变量
@host = http://localhost:8080

GET {{host}}/test/hello

###

POST {{host}}/test/echo
Content-Type:  application/json

{
    "name": "tom"
}

###

###

POST {{host}}/test/delay
Content-Type:  application/json

{
    "second": 0
}

###

POST {{host}}/test/jooq
Content-Type:  application/json

